
version: 2

# models:
#   - name: my_first_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         tests:
#           - unique
#           - not_null

#   - name: my_second_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         tests:
#           - unique
#           - not_null

sources:
  - name: nhl_stats
    meta:
      external_location: "parquet_scan('gs://nhl-data-snapshots/{name}/*/*.parquet', hive_partitioning=1)"
    tables:
      - name: nhl_player_game_stats
      - name: nhl_team_game_stats